config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :digitals
    end

    resources :orders do
      member do
        get :reset_digitals  
      end
    end
  end
  
  get '/digital/:secret', :to => 'digitals#show', :as => 'digital', :constraints => { :secret => /[a-zA-Z0-9]{30}/ }
end

app/models/spree/calculator/shipping/digital_delivery.rb
# https://github.com/spree/spree/issues/1439
require_dependency 'spree/shipping_calculator'

module Spree
  module Calculator::Shipping
    class DigitalDelivery < ShippingCalculator
      preference :amount, :decimal, default: 0
      preference :currency, :string, default: ->{ Spree::Config[:currency] }

      def self.description
        Spree.t(:digital_delivery, scope: 'digital')
      end

      def compute_package(package=nil)
        self.preferred_amount
      end

      def available?(package)
        package.contents.all? { |content| content.variant.digital? }
      end
    end
  end
end

app/models/spree/digital.rb
module Spree
  class Digital < ActiveRecord::Base
    belongs_to :variant
    has_many :digital_links, dependent: :destroy

    has_one_attached :attachment
    validates :attachment, attached: true
  end
end

app/models/spree/digital_link.rb
module Spree
  class DigitalLink < ActiveRecord::Base
    
    belongs_to :digital
    validates :digital, :presence => true

    belongs_to :line_item
    
    validates_length_of :secret, :is => 30
    
    before_validation :set_defaults, :on => :create
    
    # Can this link stil be used? It is valid if it's less than 24 hours old and was not accessed more than 3 times
    def authorizable?
      !(expired? || access_limit_exceeded?)
    end

    def expired?
      self.created_at <= Spree::DigitalConfiguration[:authorized_days].day.ago
    end

    def access_limit_exceeded?
      self.access_counter >= Spree::DigitalConfiguration[:authorized_clicks]
    end

    # This method should be called when a download is initiated.
    # It returns +true+ or +false+ depending on whether the authorization is granted.
    def authorize!
      authorizable? && increment!(:access_counter) ? true : false
    end

    def reset!
      update_column :access_counter, 0
      update_column :created_at, Time.now
    end

    private
    
    # Populating the secret automatically and zero'ing the access_counter (otherwise it might turn out to be NULL)
    def set_defaults
      self.secret = SecureRandom.hex(15)
      self.access_counter ||= 0
    end
  end
end

app/models/spree/line_item_decorator.rb
module Spree
  module LineItemDecorator
    def self.prepended(base)
      base.has_many :digital_links, :dependent => :destroy
      base.after_save :create_digital_links, :if => :digital?
    end

    def digital?
      variant.digital?
    end

    private
    # TODO there is no reason to create the digital links until the order is complete
    # TODO: PMG - Shouldn't we only do this if the quantity changed?
    def create_digital_links
      digital_links.delete_all

      #include master variant digitals
      master = variant.product.master
      if(master.digital?)
        create_digital_links_for_variant(master)
      end
      create_digital_links_for_variant(variant) unless variant.is_master
    end

    def create_digital_links_for_variant(variant)
      variant.digitals.each do |digital|
        self.quantity.times do
          digital_links.create!(:digital => digital)
        end
      end
    end
  end
end

::Spree::LineItem.prepend(Spree::LineItemDecorator)

app/models/spree/order_decorator.rb
module Spree
  module OrderDecorator
    # all products are digital
    def digital?
      line_items.all? { |item| item.digital? }
    end

    def some_digital?
      line_items.any? { |item| item.digital? }
    end

    def digital_line_items
      line_items.select(&:digital?)
    end

    def digital_links
      digital_line_items.map(&:digital_links).flatten
    end

    def reset_digital_links!
      digital_links.each do |digital_link|
        digital_link.reset!
      end
    end
  end
end

::Spree::Order.prepend(Spree::OrderDecorator)

app/models/spree/product_decorator.rb
module Spree
  module ProductDecorator
    def self.prepended(base)
      base.has_many :digitals, :through => :variants_including_master
    end
  end
end

::Spree::Product.prepend(Spree::ProductDecorator)

app/models/spree/stock/splitter/digital.rb
module Spree
  module Stock
    module Splitter
      class Digital < Base
        def split(packages)
          split_packages = []
          packages.each do |package|
            split_packages += split_by_digital(package)
          end
          return_next split_packages
        end

        private
        def split_by_digital(package)
          digitals = Hash.new { |hash, key| hash[key] = [] }
          package.contents.each do |item|
            digitals[item.variant.digital?] << item
          end
          hash_to_packages(digitals)
        end

        def hash_to_packages(digitals)
          packages = []
          digitals.each do |id, contents|
            packages << build_package(contents)
          end
          packages
        end
      end
    end
  end
end

app/models/spree/variant_decorator.rb
module Spree
  module VariantDecorator
    def self.prepended(base)
      base.has_many :digitals
      base.after_save :destroy_digital, :if => :deleted?
    end

    # Is this variant to be downloaded by the customer?
    def digital?
      digitals.present?
    end

    private

    # :dependent => :destroy needs to be handled manually
    # spree does not delete variants, just marks them as deleted?
    # optionally keep digitals around for customers who require continued access to their purchases
    def destroy_digital
      digitals.map &:destroy unless Spree::DigitalConfiguration[:keep_digitals]
    end
  end
end

::Spree::Variant.prepend(Spree::VariantDecorator)

app/controllers/spree/admin/digitals_controller.rb
module Spree
  module Admin
    class DigitalsController < ResourceController
      belongs_to "spree/product", :find_by => :slug

      def create
        invoke_callbacks(:create, :before)
        @object.attributes = permitted_resource_params
        @object.attributes = add_additional_paramas if params[:digital][:attachment]

        if @object.valid?
          super
        else
          invoke_callbacks(:create, :fails)
          flash[:error] = @object.errors.full_messages.join(", ")
          redirect_to location_after_save
        end
      end

      protected
        def location_after_save
          spree.admin_product_digitals_path(@product)
        end

      def permitted_resource_params
        params.require(:digital).permit(permitted_digital_attributes)
      end

      def permitted_digital_attributes
        [:variant_id, :attachment, :attachment_file_name, :attachment_content_type]
      end

      def add_additional_paramas
        hash = {}
        hash[:attachment_file_name] = params[:digital][:attachment].original_filename
        hash[:attachment_content_type] = params[:digital][:attachment].content_type
        hash
      end
    end
  end
end

app/controllers/spree/admin/orders_controller_decorator.rb
module Spree
  module Admin
    module OrdersControllerDecorator
      def reset_digitals
        load_order
        @order.reset_digital_links!
        flash[:notice] = Spree.t(:downloads_reset, scope: 'digitals')
        redirect_to spree.edit_admin_order_path(@order)
      end
    end
  end
end

::Spree::Admin::OrdersController.prepend(Spree::Admin::OrdersControllerDecorator)

app/controllers/spree/digitals_controller.rb
module Spree
  class DigitalsController < Spree::BaseController
    def show
      if attachment.present?
        if digital_link.authorize!
          if Rails.application.config.active_storage.service == :amazon
            redirect_to attachment.expiring_url(Spree::DigitalConfiguration[:s3_expiration_seconds]) and return
          else
            send_file(
              ActiveStorage::Blob.service.path_for(attachment.key),
              filename: attachment.record.attachment_file_name,
              type: attachment.record.attachment_content_type,
              status: :ok
            ) and return
          end
        end
      else
        Rails.logger.error "Missing Digital Item: attachment"
      end

      render :unauthorized
    end

    private

      def digital_link
        @link ||= DigitalLink.find_by!(secret: params[:secret])
      end

      def attachment
        @attachment ||= digital_link.digital.try(:attachment) if digital_link.present?
      end
  end
end

app/views/spree/admin/digitals/_digital.html.erb
<% if digital.attachment_file_name.present? %>
  <%= digital.attachment_file_name %> (<%= number_to_human_size(digital.attachment_file_size) %>)
<% else %>
  <%= Spree.t(:broken_file, scope: 'digitals') %>
<% end %>

app/views/spree/admin/digitals/_form.html.erb
<div>
  <%= form_for(:digital, :url => admin_product_digitals_path(@product), :method => :create, :multipart => true ) do |f| %>
    <fieldset>
      <legend class='h4 pl-0 <%= variant.digital? ? "mb-0" : "mb-3" %>'><%= Spree::Variant.model_name.human %> "<%= variant.is_master ? "Master" : variant.options_text %>"</legend>
      <% if variant.digital? %>
        <table class="table">
          <thead>
            <tr>
              <th><%= Spree.t(:file_name, scope: "spree_digital") %></th>
              <th class="actions"></th>
            </tr>
          </thead>
          <tbody>
          <% variant.digitals.each do |digital| %>
            <tr>
              <td><%= render digital %></td>
              <td class="actions text-right">
                <%= link_to_with_icon 'delete', Spree.t(:delete_file, scope: 'digitals'), admin_product_digital_url(@product, digital), data: {confirm: Spree.t(:delete_file_confirmation, scope: 'digitals', filename: digital.attachment_file_name)}, method: :delete, class: 'btn btn-danger btn-sm delete-resource' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>

      <div class="form-group">
        <%= f.label :file, Spree.t(:add_new_file, scope: 'digitals') %> <span class="required">*</span><br/>
        <%= f.file_field :attachment %>
        <%= hidden_field_tag 'digital[variant_id]', variant.id %>
        <%= button Spree.t(:upload, scope: "spree_digital"), 'add', 'submit', { :class => "btn btn-primary" } %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/digitals/index.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/product' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Digital Versions"} %>

<% if @product.has_variants? %>

  <% for variant in @product.variants_including_master do %>
    <%= render 'form', :variant => variant %>
  <% end %>

<% else %>
  <p><%= Spree.t('product.has_no_variants') %><p>

  <% if @product.master.digital? %>
    A digital version of this product currently exists:
    <%= render @product.master.digitals %>
  <% end %>

  <%= render 'form', :variant => @product.master %>

<% end %>

app/views/spree/digitals/_digital.html.erb
<% if digital.attachment_file_name.present? %>
  <%= digital.attachment_file_name %> (<%= number_to_human_size(digital.attachment.blob.byte_size) %>)
<% else %>
  <%= Spree.t(:broken_file, scope: 'digitals') %>
<% end %>

app/views/spree/digitals/unauthorized.html.erb
<% if defined?(SpreeFancy) %>
  <% content_for :subheader do %>
    <h1><%= Spree.t(:unauthorized, scope: 'digitals.unauthorized') %></h1>
  <% end %>
<% else %>
  <h1><%= Spree.t(:unauthorized, scope: 'digitals.unauthorized') %></h1>
<% end %>

<%= Spree.t(:explained, scope: 'digitals.unauthorized') %>